### ISSUE TITLE
Missing prerequisites and other README needs

### ISSUE THREAD

**Issue by luzpaz** [Francisco-Rosa/FreeCAD-Movie#12]
* What version of FreeCAD does the addon support? 
* What 3rd party dependencies are required? 
* What minimum version of Render WB? (even though it's optional)

Can theses be specified in the README? 

Would it be possible to display an animation or 2, that show the workbench in action?

**Comment by Francisco-Rosa** [comment]
The workbench works with FC 0.20 and 0.21 versions. 
In general, there are no required dependencies. It has been tested on Linux and Windows systems, but not tested on MacOS. On Linux based on Arch, it asks for the installation of OpenCV, but on this same system, if you use Appimage, this does not happen.
To better take advantage of this workbench's resources in renderings, it is recommended to work with the most recent versions of the Render workbench (2023.02.05).
Yes, these observations can be in README ou TUTORIAL.
And yes, I'm preparing some videos on how to use the workbench.

luzpaz,
Could you help us with the LuxCore renders?

**Comment by luzpaz** [comment]
You can add the minimum version of Render workbench to the depend tag  https://github.com/Francisco-Rosa/FreeCAD-Movie/blob/master/package.xml#L28  with the `version_gte="VERSION"` attribute. See https://wiki.freecad.org/Package_Metadata#Attributes_6 for more details

> Could you help us with the LuxCore renders?  

How can I help ?

**Comment by Francisco-Rosa** [comment]
To continue generating images rendered in sequence, LuxCore must close its window at the end of each render, or in this case when a certain number of samples per pixel is reached. We need to know what the command inside LuxCore would be for it to close the window and add it in the Render workbench. Do you know it? See also:

https://forum.freecad.org/viewtopic.php?t=55297&start=50
    Em quarta-feira, 14 de junho de 2023 às 19:50:27 BRT, luzpaz ***@***.***> escreveu:  
 
 


You can add the minimum version of Render workbench to the depend tag https://github.com/Francisco-Rosa/FreeCAD-Movie/blob/master/package.xml#L28 with the version_gte="VERSION" attribute. See https://wiki.freecad.org/Package_Metadata#Attributes_6 for more details


Could you help us with the LuxCore renders?


How can I help ?

**Comment by luzpaz** [comment]
@Francisco-Rosa is there a ticket open for the luxcore issue? If not, then one should be opened. I don't know luxcore at all but we can maybe get someone on their team/community to collaborate with?

**Comment by luzpaz** [comment]
bump
