### ISSUE TITLE
Readme. Not polylines

### ISSUE THREAD

**Issue by MiqCG** [Francisco-Rosa/FreeCAD-Movie#26]
In the Readme file, in two occasions is explained what types of lines/segments can be used to indicate a movie path. I think it's convenient to explicitly indicate that Polylines cannot be used because it will imply stops in every intermediate point.

"To make that the Movie Camera follows a route, you must create a segment first to do so. It can be a line, arc, circle, ellipse, B-spline or Bézier curve, from Sketcher or Draft Workbenches. Select the segment created in Cam_Route_Selection property. Configure the remaining camera properties."

"To make that the Movie Objects follows a route, you must create a segment first to do so. It can be a line, arc, circle, ellipse, B-spline or Bézier curve, from Sketcher or Draft Workbenches. Select the segment created in Objects_Route_Selection property. Configure the remaining object properties."

**Comment by Francisco-Rosa** [comment]
Thank you MiqCG. Warning already included.
