### ISSUE TITLE
Readme: Connection.py

### ISSUE THREAD

**Issue by MiqCG** [Francisco-Rosa/FreeCAD-Movie#28]
In the Readme file 
"If you want to use an animation from another workbench, script or macro of FreeCAD, it is necessary to prepare the connection module for using them (ex. [Modified ExplodedAssembly](https://github.com/Francisco-Rosa/ExplodedAssembly)). For this, see the instructions inside the [Connection.py](https://github.com/Francisco-Rosa/FreeCAD-Movie/blob/master/Connection.py)."

The link to connection.py is broken or the file doesn't exist.
404 - page not found

**Comment by Francisco-Rosa** [comment]
Thank you MiqCG. The problem was solved.
